[build-system]
requires = ["setuptools>=42", "wheel","cibuildwheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tracET"
version = "2.2.2"
authors = [
    {name = "Pelayo Alvarez-Brecht"},
    {name = "Antonio Martinez-Sanchez"}
]
description = "A package that could transform a scalar map in a point cloud, trace a graph for filaments and compute the dice metric for two segmentations. "
readme = "README.md"

[project.urls]
Homepage ="https://guithub.com/PelayoAlvarezBrecht/tracer/tree/nih/"

[project.scripts]
get_saliency = "tracET.scripts.get_saliency:main"
apply_nonmaxsup = "tracET.scripts.apply_nonmaxsup:main"
trace_graph = "tracET.scripts.trace_graph:main"
get_cluster = "tracET.scripts.Get_cluster:main"
membrane_poly = "tracET.scripts.membrane_poly:main"
seg_skel_dice = "tracET.scripts.seg_skel_dice:main"

[tool.cibuildwheel]
platform = "linux"
